### ISSUE TITLE
Build types are removed from build when release-opinion plugin is applied

### ISSUE THREAD

**Issue by jvff** [ajoberstar/gradle-git#211] opened 2016-08-15 17:13 UTC
I am using a Gradle multi-project build, and I would like to apply the plugin to a single sub-project that's a native library and have other sub-projects link to that sub-project without applying the plugin. I think it should work, but somehow the build types I specified on the root project get ignored when the plugin is applied, leading to sub-projects complaining about not finding the library of the sub-project that had the plugin applied.

I've created a "demo repo" to reproduce the bug: https://github.com/jvff/gradle-git-build-type-issue . I've created commits [with](https://github.com/jvff/gradle-git-build-type-issue/commit/71af034ef8d436b898fbd5f9a18c137dfebd5702) and [without](https://github.com/jvff/gradle-git-build-type-issue/commit/b10eff4bbd7414f06839509f52f3c38b855714ef) the plugin applied (tags: [with_bug](https://github.com/jvff/gradle-git-build-type-issue/tree/with_bug) and [without_bug](https://github.com/jvff/gradle-git-build-type-issue/tree/without_bug)), and I've also added the log files to the repository ([commit](https://github.com/jvff/gradle-git-build-type-issue/commit/ac57a1cb0bca7055d6506e66b4f2ef74f9cce09c) tagged as: [logs](https://github.com/jvff/gradle-git-build-type-issue/tree/logs)).

If you need anything else, please let me know.

**Comment by jvff** [comment] 2016-08-15 18:27
I've managed to narrow it down to being a name problem. With the extension and the task being called "release", which is the same as the build type name, the build types aren't used (maybe because the name was shadowed, and either it doesn't use build types when there's only one, or it Gradle has a failure when handling such scenario?).

Now, the possible workarounds are simple:

1. Change the build type name to something else (for example: production)
2. Manually change `org.ajoberstar.gradle.git.release.base.BaseReleasePlugin` to rename the extension and the task names:
   * Change `RELEASE_TASK_NAME` to something else ('gitrelease', 'tag'?)
   * Change `project.extensions.create('release',` ... to change the `'release'` name to something else

The final questions are:

1. Should Gradle have handled this differently (i.e., failed on shadow error, or distinguished when `release` means task or extension and when `release` means build type)
2. Given that `debug` and `release` seem to be standard names (at least as represented in the [Gradle docs](https://docs.gradle.org/current/userguide/native_software.html#native_binaries:variants)), should the extension and task of this plugin change their names?

**Comment by ajoberstar** [comment] 2016-08-15 23:46
This looks like a duplicate of #206, but thanks for the extra information. Please follow over there.

**Closed by ajoberstar** 2016-08-15 23:46 UTC
Labels: duplicate
